(cl:in-package ds4_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          AXIS_LEFT_X-VAL
          AXIS_LEFT_X
          AXIS_LEFT_Y-VAL
          AXIS_LEFT_Y
          AXIS_RIGHT_X-VAL
          AXIS_RIGHT_X
          AXIS_RIGHT_Y-VAL
          AXIS_RIGHT_Y
          AXIS_L2-VAL
          AXIS_L2
          AXIS_R2-VAL
          AXIS_R2
          BUTTON_DPAD_UP-VAL
          BUTTON_DPAD_UP
          BUTTON_DPAD_DOWN-VAL
          BUTTON_DPAD_DOWN
          BUTTON_DPAD_LEFT-VAL
          BUTTON_DPAD_LEFT
          BUTTON_DPAD_RIGHT-VAL
          BUTTON_DPAD_RIGHT
          BUTTON_CROSS-VAL
          BUTTON_CROSS
          BUTTON_CIRCLE-VAL
          BUTTON_CIRCLE
          BUTTON_SQUARE-VAL
          BUTTON_SQUARE
          BUTTON_TRIANGLE-VAL
          BUTTON_TRIANGLE
          BUTTON_L1-VAL
          BUTTON_L1
          BUTTON_L2-VAL
          BUTTON_L2
          BUTTON_L3-VAL
          BUTTON_L3
          BUTTON_R1-VAL
          BUTTON_R1
          BUTTON_R2-VAL
          BUTTON_R2
          BUTTON_R3-VAL
          BUTTON_R3
          BUTTON_SHARE-VAL
          BUTTON_SHARE
          BUTTON_OPTIONS-VAL
          BUTTON_OPTIONS
          BUTTON_TRACKPAD-VAL
          BUTTON_TRACKPAD
          BUTTON_PS-VAL
          BUTTON_PS
          IMU-VAL
          IMU
          BATTERY_PERCENTAGE-VAL
          BATTERY_PERCENTAGE
          BATTERY_FULL_CHARGING-VAL
          BATTERY_FULL_CHARGING
          TOUCH0-VAL
          TOUCH0
          TOUCH1-VAL
          TOUCH1
          PLUG_USB-VAL
          PLUG_USB
          PLUG_AUDIO-VAL
          PLUG_AUDIO
          PLUG_MIC-VAL
          PLUG_MIC
))