(cl:in-package ds4_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          LEFT_ANALOG_X-VAL
          LEFT_ANALOG_X
          LEFT_ANALOG_Y-VAL
          LEFT_ANALOG_Y
          RIGHT_ANALOG_X-VAL
          RIGHT_ANALOG_X
          RIGHT_ANALOG_Y-VAL
          RIGHT_ANALOG_Y
          L2_ANALOG-VAL
          L2_ANALOG
          R2_ANALOG-VAL
          R2_ANALOG
          DPAD_UP-VAL
          DPAD_UP
          DPAD_DOWN-VAL
          DPAD_DOWN
          DPAD_LEFT-VAL
          DPAD_LEFT
          DPAD_RIGHT-VAL
          DPAD_RIGHT
          BUTTON_CROSS-VAL
          BUTTON_CROSS
          BUTTON_CIRCLE-VAL
          BUTTON_CIRCLE
          BUTTON_SQUARE-VAL
          BUTTON_SQUARE
          BUTTON_TRIANGLE-VAL
          BUTTON_TRIANGLE
          BUTTON_L1-VAL
          BUTTON_L1
          BUTTON_L2-VAL
          BUTTON_L2
          BUTTON_L3-VAL
          BUTTON_L3
          BUTTON_R1-VAL
          BUTTON_R1
          BUTTON_R2-VAL
          BUTTON_R2
          BUTTON_R3-VAL
          BUTTON_R3
          BUTTON_SHARE-VAL
          BUTTON_SHARE
          BUTTON_OPTIONS-VAL
          BUTTON_OPTIONS
          BUTTON_TRACKPAD-VAL
          BUTTON_TRACKPAD
          BUTTON_PS-VAL
          BUTTON_PS
          LIN_ACC_X-VAL
          LIN_ACC_X
          LIN_ACC_Y-VAL
          LIN_ACC_Y
          LIN_ACC_Z-VAL
          LIN_ACC_Z
          ANG_VEL_X-VAL
          ANG_VEL_X
          ANG_VEL_Y-VAL
          ANG_VEL_Y
          ANG_VEL_Z-VAL
          ANG_VEL_Z
          TRACKPAD_TOUCH0_ID-VAL
          TRACKPAD_TOUCH0_ID
          TRACKPAD_TOUCH0_ACTIVE-VAL
          TRACKPAD_TOUCH0_ACTIVE
          TRACKPAD_TOUCH0_X-VAL
          TRACKPAD_TOUCH0_X
          TRACKPAD_TOUCH0_Y-VAL
          TRACKPAD_TOUCH0_Y
          TRACKPAD_TOUCH1_ID-VAL
          TRACKPAD_TOUCH1_ID
          TRACKPAD_TOUCH1_ACTIVE-VAL
          TRACKPAD_TOUCH1_ACTIVE
          TRACKPAD_TOUCH1_X-VAL
          TRACKPAD_TOUCH1_X
          TRACKPAD_TOUCH1_Y-VAL
          TRACKPAD_TOUCH1_Y
          TIMESTAMP-VAL
          TIMESTAMP
          BATTERY-VAL
          BATTERY
          PLUG_USB-VAL
          PLUG_USB
          PLUG_AUDIO-VAL
          PLUG_AUDIO
          PLUG_MIC-VAL
          PLUG_MIC
))