// Generated by gencpp from file messages/Fusion.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_FUSION_H
#define MESSAGES_MESSAGE_FUSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <messages/Object.h>

namespace messages
{
template <class ContainerAllocator>
struct Fusion_
{
  typedef Fusion_<ContainerAllocator> Type;

  Fusion_()
    : objects()
    , distance()
    , angle()
    , fps(0.0)  {
    }
  Fusion_(const ContainerAllocator& _alloc)
    : objects(_alloc)
    , distance(_alloc)
    , angle(_alloc)
    , fps(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::messages::Object_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::messages::Object_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _distance_type;
  _distance_type distance;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _angle_type;
  _angle_type angle;

   typedef float _fps_type;
  _fps_type fps;





  typedef boost::shared_ptr< ::messages::Fusion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::Fusion_<ContainerAllocator> const> ConstPtr;

}; // struct Fusion_

typedef ::messages::Fusion_<std::allocator<void> > Fusion;

typedef boost::shared_ptr< ::messages::Fusion > FusionPtr;
typedef boost::shared_ptr< ::messages::Fusion const> FusionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::Fusion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::Fusion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messages::Fusion_<ContainerAllocator1> & lhs, const ::messages::Fusion_<ContainerAllocator2> & rhs)
{
  return lhs.objects == rhs.objects &&
    lhs.distance == rhs.distance &&
    lhs.angle == rhs.angle &&
    lhs.fps == rhs.fps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messages::Fusion_<ContainerAllocator1> & lhs, const ::messages::Fusion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::messages::Fusion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::Fusion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::Fusion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::Fusion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Fusion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Fusion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::Fusion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66bc9b2b4c1ac988d3c692a1eb52fe22";
  }

  static const char* value(const ::messages::Fusion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66bc9b2b4c1ac988ULL;
  static const uint64_t static_value2 = 0xd3c692a1eb52fe22ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::Fusion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/Fusion";
  }

  static const char* value(const ::messages::Fusion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::Fusion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Human detection with distance\n"
"\n"
"#objects(Boat) in Image\n"
"Object[] objects\n"
"\n"
"#distance\n"
"float32[] distance\n"
"\n"
"#angle\n"
"float32[] angle\n"
"\n"
"# Current FPS Performance\n"
"float32 fps\n"
"\n"
"================================================================================\n"
"MSG: messages/Object\n"
"std_msgs/Header header\n"
"\n"
"# Bounding boxes in pixels\n"
"sensor_msgs/RegionOfInterest box\n"
"\n"
"# String class\n"
"string class_name\n"
"\n"
"# Float probability scores of the class\n"
"float32 score\n"
"\n"
"# Instance masks as Image\n"
"sensor_msgs/Image mask\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/RegionOfInterest\n"
"# This message is used to specify a region of interest within an image.\n"
"#\n"
"# When used to specify the ROI setting of the camera when the image was\n"
"# taken, the height and width fields should either match the height and\n"
"# width fields for the associated image; or height = width = 0\n"
"# indicates that the full resolution image was captured.\n"
"\n"
"uint32 x_offset  # Leftmost pixel of the ROI\n"
"                 # (0 if the ROI includes the left edge of the image)\n"
"uint32 y_offset  # Topmost pixel of the ROI\n"
"                 # (0 if the ROI includes the top edge of the image)\n"
"uint32 height    # Height of ROI\n"
"uint32 width     # Width of ROI\n"
"\n"
"# True if a distinct rectified ROI should be calculated from the \"raw\"\n"
"# ROI in this message. Typically this should be False if the full image\n"
"# is captured (ROI not used), and True if a subwindow is captured (ROI\n"
"# used).\n"
"bool do_rectify\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::messages::Fusion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::Fusion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objects);
      stream.next(m.distance);
      stream.next(m.angle);
      stream.next(m.fps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Fusion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::Fusion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::Fusion_<ContainerAllocator>& v)
  {
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::messages::Object_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
    s << indent << "distance[]" << std::endl;
    for (size_t i = 0; i < v.distance.size(); ++i)
    {
      s << indent << "  distance[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.distance[i]);
    }
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angle[i]);
    }
    s << indent << "fps: ";
    Printer<float>::stream(s, indent + "  ", v.fps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_FUSION_H
