// Generated by gencpp from file messages/s.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_S_H
#define MESSAGES_MESSAGE_S_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct s_
{
  typedef s_<ContainerAllocator> Type;

  s_()
    : s()
    , s_dot()  {
    }
  s_(const ContainerAllocator& _alloc)
    : s(_alloc)
    , s_dot(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _s_type;
  _s_type s;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _s_dot_type;
  _s_dot_type s_dot;





  typedef boost::shared_ptr< ::messages::s_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::s_<ContainerAllocator> const> ConstPtr;

}; // struct s_

typedef ::messages::s_<std::allocator<void> > s;

typedef boost::shared_ptr< ::messages::s > sPtr;
typedef boost::shared_ptr< ::messages::s const> sConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::s_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::s_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messages::s_<ContainerAllocator1> & lhs, const ::messages::s_<ContainerAllocator2> & rhs)
{
  return lhs.s == rhs.s &&
    lhs.s_dot == rhs.s_dot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messages::s_<ContainerAllocator1> & lhs, const ::messages::s_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::messages::s_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::s_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::s_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::s_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::s_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::s_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::s_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14fb056663501f0195cd852f090d3a8f";
  }

  static const char* value(const ::messages::s_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14fb056663501f01ULL;
  static const uint64_t static_value2 = 0x95cd852f090d3a8fULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::s_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/s";
  }

  static const char* value(const ::messages::s_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::s_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] s\n"
"float64[] s_dot\n"
;
  }

  static const char* value(const ::messages::s_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::s_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
      stream.next(m.s_dot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct s_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::s_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::s_<ContainerAllocator>& v)
  {
    s << indent << "s[]" << std::endl;
    for (size_t i = 0; i < v.s.size(); ++i)
    {
      s << indent << "  s[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.s[i]);
    }
    s << indent << "s_dot[]" << std::endl;
    for (size_t i = 0; i < v.s_dot.size(); ++i)
    {
      s << indent << "  s_dot[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.s_dot[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_S_H
