// Generated by gencpp from file messages/s_message.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_S_MESSAGE_H
#define MESSAGES_MESSAGE_S_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct s_message_
{
  typedef s_message_<ContainerAllocator> Type;

  s_message_()
    : s(0.0)
    , s_dot(0.0)  {
    }
  s_message_(const ContainerAllocator& _alloc)
    : s(0.0)
    , s_dot(0.0)  {
  (void)_alloc;
    }



   typedef double _s_type;
  _s_type s;

   typedef double _s_dot_type;
  _s_dot_type s_dot;





  typedef boost::shared_ptr< ::messages::s_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::s_message_<ContainerAllocator> const> ConstPtr;

}; // struct s_message_

typedef ::messages::s_message_<std::allocator<void> > s_message;

typedef boost::shared_ptr< ::messages::s_message > s_messagePtr;
typedef boost::shared_ptr< ::messages::s_message const> s_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::s_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::s_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messages::s_message_<ContainerAllocator1> & lhs, const ::messages::s_message_<ContainerAllocator2> & rhs)
{
  return lhs.s == rhs.s &&
    lhs.s_dot == rhs.s_dot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messages::s_message_<ContainerAllocator1> & lhs, const ::messages::s_message_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::messages::s_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::s_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::s_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::s_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::s_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::s_message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::s_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44991c89fe9397efcd14043a99f9f1c5";
  }

  static const char* value(const ::messages::s_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44991c89fe9397efULL;
  static const uint64_t static_value2 = 0xcd14043a99f9f1c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::s_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/s_message";
  }

  static const char* value(const ::messages::s_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::s_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 s\n"
"float64 s_dot\n"
;
  }

  static const char* value(const ::messages::s_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::s_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
      stream.next(m.s_dot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct s_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::s_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::s_message_<ContainerAllocator>& v)
  {
    s << indent << "s: ";
    Printer<double>::stream(s, indent + "  ", v.s);
    s << indent << "s_dot: ";
    Printer<double>::stream(s, indent + "  ", v.s_dot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_S_MESSAGE_H
