// Generated by gencpp from file messages/state_estimation.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_STATE_ESTIMATION_H
#define MESSAGES_MESSAGE_STATE_ESTIMATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct state_estimation_
{
  typedef state_estimation_<ContainerAllocator> Type;

  state_estimation_()
    : eta_hat()
    , nu_hat()
    , bias_hat()  {
    }
  state_estimation_(const ContainerAllocator& _alloc)
    : eta_hat(_alloc)
    , nu_hat(_alloc)
    , bias_hat(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _eta_hat_type;
  _eta_hat_type eta_hat;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _nu_hat_type;
  _nu_hat_type nu_hat;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _bias_hat_type;
  _bias_hat_type bias_hat;





  typedef boost::shared_ptr< ::messages::state_estimation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::state_estimation_<ContainerAllocator> const> ConstPtr;

}; // struct state_estimation_

typedef ::messages::state_estimation_<std::allocator<void> > state_estimation;

typedef boost::shared_ptr< ::messages::state_estimation > state_estimationPtr;
typedef boost::shared_ptr< ::messages::state_estimation const> state_estimationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::state_estimation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::state_estimation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messages::state_estimation_<ContainerAllocator1> & lhs, const ::messages::state_estimation_<ContainerAllocator2> & rhs)
{
  return lhs.eta_hat == rhs.eta_hat &&
    lhs.nu_hat == rhs.nu_hat &&
    lhs.bias_hat == rhs.bias_hat;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messages::state_estimation_<ContainerAllocator1> & lhs, const ::messages::state_estimation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::messages::state_estimation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::state_estimation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::state_estimation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::state_estimation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::state_estimation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::state_estimation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::state_estimation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f1bb4322eba02c2ff0b75462df79905";
  }

  static const char* value(const ::messages::state_estimation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f1bb4322eba02c2ULL;
  static const uint64_t static_value2 = 0xff0b75462df79905ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::state_estimation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/state_estimation";
  }

  static const char* value(const ::messages::state_estimation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::state_estimation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] eta_hat\n"
"float64[] nu_hat\n"
"float64[] bias_hat\n"
;
  }

  static const char* value(const ::messages::state_estimation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::state_estimation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.eta_hat);
      stream.next(m.nu_hat);
      stream.next(m.bias_hat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct state_estimation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::state_estimation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::state_estimation_<ContainerAllocator>& v)
  {
    s << indent << "eta_hat[]" << std::endl;
    for (size_t i = 0; i < v.eta_hat.size(); ++i)
    {
      s << indent << "  eta_hat[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.eta_hat[i]);
    }
    s << indent << "nu_hat[]" << std::endl;
    for (size_t i = 0; i < v.nu_hat.size(); ++i)
    {
      s << indent << "  nu_hat[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.nu_hat[i]);
    }
    s << indent << "bias_hat[]" << std::endl;
    for (size_t i = 0; i < v.bias_hat.size(); ++i)
    {
      s << indent << "  bias_hat[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.bias_hat[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_STATE_ESTIMATION_H
