# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from messages/guidance_signals.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class guidance_signals(genpy.Message):
  _md5sum = "fd30d3a050e6c9293f8dcca19a9c94ca"
  _type = "messages/guidance_signals"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64[] eta_d
float64[] pd_s1
float64[] pd_s2
float64[] pd_ss1
float64[] pd_ss2
float64 psi_d_dot
float64 psi_d_ddot
"""
  __slots__ = ['eta_d','pd_s1','pd_s2','pd_ss1','pd_ss2','psi_d_dot','psi_d_ddot']
  _slot_types = ['float64[]','float64[]','float64[]','float64[]','float64[]','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       eta_d,pd_s1,pd_s2,pd_ss1,pd_ss2,psi_d_dot,psi_d_ddot

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(guidance_signals, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.eta_d is None:
        self.eta_d = []
      if self.pd_s1 is None:
        self.pd_s1 = []
      if self.pd_s2 is None:
        self.pd_s2 = []
      if self.pd_ss1 is None:
        self.pd_ss1 = []
      if self.pd_ss2 is None:
        self.pd_ss2 = []
      if self.psi_d_dot is None:
        self.psi_d_dot = 0.
      if self.psi_d_ddot is None:
        self.psi_d_ddot = 0.
    else:
      self.eta_d = []
      self.pd_s1 = []
      self.pd_s2 = []
      self.pd_ss1 = []
      self.pd_ss2 = []
      self.psi_d_dot = 0.
      self.psi_d_ddot = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.eta_d)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.eta_d))
      length = len(self.pd_s1)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.pd_s1))
      length = len(self.pd_s2)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.pd_s2))
      length = len(self.pd_ss1)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.pd_ss1))
      length = len(self.pd_ss2)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.pd_ss2))
      _x = self
      buff.write(_get_struct_2d().pack(_x.psi_d_dot, _x.psi_d_ddot))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.eta_d = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pd_s1 = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pd_s2 = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pd_ss1 = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pd_ss2 = s.unpack(str[start:end])
      _x = self
      start = end
      end += 16
      (_x.psi_d_dot, _x.psi_d_ddot,) = _get_struct_2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.eta_d)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.eta_d.tostring())
      length = len(self.pd_s1)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.pd_s1.tostring())
      length = len(self.pd_s2)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.pd_s2.tostring())
      length = len(self.pd_ss1)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.pd_ss1.tostring())
      length = len(self.pd_ss2)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.pd_ss2.tostring())
      _x = self
      buff.write(_get_struct_2d().pack(_x.psi_d_dot, _x.psi_d_ddot))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.eta_d = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pd_s1 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pd_s2 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pd_ss1 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pd_ss2 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 16
      (_x.psi_d_dot, _x.psi_d_ddot,) = _get_struct_2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
